# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  # GCB doesn't clone submodules and removes .git directory, so we fetch the
  # current $COMMIT_SHA and clone the submodules manually.
  - name: 'nixos/nix:2.3.4'
    id: recover_git_folder
    entrypoint: 'nix-shell'
    args: ['-p', '[bash git coreutils]', '--run',
      '[ ! -d ".git" ] && echo "Recreating .git folder" && git clone -v https://github.com/project-oak/silveroak.git --no-checkout oak-hardware-git && mv oak-hardware-git/.git . && git fetch -v origin $COMMIT_SHA && git checkout -f $COMMIT_SHA && git submodule update --init --recursive || true']

  - name: 'nixos/nix:2.3.4'
    id: cache_dependencies
    waitFor: ['recover_git_folder']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_third_party
    waitFor: ['recover_git_folder']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'make -j32 third_party']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: make_cava_coq
    waitFor: ['build_third_party']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'make -j32 -C cava coq']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_verilator
    waitFor: ['build_third_party']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['verilator.nix']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: make_all
    waitFor: ['build_verilator', 'make_cava_coq']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['verilator.nix', '--run', 'make -j32']
    volumes:
    - name: nix-store
      path: /nix/
timeout: 30m

options:
  # See: https://cloud.google.com/compute/docs/machine-types
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
