# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  # GCB doesn't clone submodules and removes .git directory, so we fetch the
  # current $COMMIT_SHA and clone the submodules manually.
  - name: 'nixos/nix:2.3.10'
    id: recover_git_folder
    entrypoint: 'nix-shell'
    args: ['-p', '[bash git coreutils]', '--run',
      '[ ! -d ".git" ] && echo "Recreating .git folder" && git clone -v https://github.com/project-oak/silveroak.git --no-checkout oak-hardware-git && mv oak-hardware-git/.git . && git fetch -v origin $COMMIT_SHA && git checkout -f $COMMIT_SHA || git submodule update --init --recursive']

  - name: 'nixos/nix:2.3.10'
    id: make_all
    waitFor: ['recover_git_folder']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'make -j32']
timeout: 30m

options:
  # See: https://cloud.google.com/compute/docs/machine-types
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
