# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  - name: 'nixos/nix:2.3.4'
    id: cache_dependencies
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'false', '--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_verilator
    waitFor: ['cache_dependencies']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'true', '--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_third_party
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'false', '--run', 'make third_party']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: run_makefile
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'git init; ls -la ./third_party/coq-ext-lib; make']
    volumes:
    - name: nix-store
      path: /nix/

timeout: 30m

options:
  # See: https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/MachineType
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
