# Reference: https://cloud.google.com/cloud-build/docs/build-config

steps:
  # GCB doesn't clone submodules and removes .git directory, so we fetch the
  # current $COMMIT_SHA and clone the submodules manually.
  # - name: 'nixos/nix:2.3.4'
  #   id: recover_git_folder
  #   entrypoint: 'nix-shell'
  #   args: ['-p', '[bash git coreutils]', '--run',
  #     'git clone -v https://github.com/project-oak/oak-hardware.git --no-checkout oak-hardware-git && mv oak-hardware-git/.git . && git fetch -v origin $COMMIT_SHA && git checkout -f $COMMIT_SHA && git submodule update --init']

  - name: 'nixos/nix:2.3.4'
    id: cache_dependencies
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'false', '--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_verilator
    waitFor: ['cache_dependencies']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'true', '--run', 'echo "Done."']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_third_party
    waitFor: ['cache_dependencies']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--arg', 'buildVerilator', 'false', '--run', 'make -j third_party']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_cava
    waitFor: ['cache_dependencies', 'build_verilator', 'build_third_party']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'make -j arrow-lib; make -j cava']
    volumes:
    - name: nix-store
      path: /nix/

  - name: 'nixos/nix:2.3.4'
    id: build_all
    waitFor: ['build_cava']
    timeout: 20m
    entrypoint: 'nix-shell'
    args: ['--run', 'make -j']
    volumes:
    - name: nix-store
      path: /nix/

timeout: 30m

options:
  # See: https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/MachineType
  machineType: 'N1_HIGHCPU_32'
  requestedVerifyOption: 'VERIFIED'
  sourceProvenanceHash: ['SHA256']
