name: 'Init base'
description: 'Init base'
inputs:
outputs:
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      submodules: 'recursive'
  - uses: cachix/install-nix-action@v12
    with:
      nix_path: nixpkgs=channel:nixos-unstable

