name: build_all

on:
  push:
  pull_request:

jobs:
  run_make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # Multiple threads causes OOM and process termination
    - run: nix-shell --run 'make -j1'
